spring:
  application:
    name: backend

  datasource:
    url: jdbc:mysql://localhost:3307/devlog?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: devlog
    password: devlog

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

server:
  port: 8080